# -*- coding: utf-8 -*-
"""FinalProjectDemo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfpFlrKa_25xSYj_oShMH1vAZOc1o6bu
"""
import os
import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
from google.cloud import language_v1
from concurrent.futures import ThreadPoolExecutor
import seaborn as sns

# Initialize Google Cloud client
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'final-project-425021-2bc8712c26ad.json'
client = language_v1.LanguageServiceClient()

def analyze_sentiment(text_content):
    try:
        document = language_v1.Document(content=text_content, type_=language_v1.Document.Type.PLAIN_TEXT)
        response = client.analyze_sentiment(request={'document': document})
        sentiment = response.document_sentiment
        return sentiment.score, sentiment.magnitude
    except Exception as e:
        st.write("Error in sentiment analysis:", e)
        return None, None

def load_data():
    data = pd.read_csv('b_fixed.csv')
    return data

df = load_data()
results = []
with ThreadPoolExecutor(max_workers=5) as executor:
    for result in executor.map(analyze_sentiment, df['Review']):
        results.append(result)

df['sentiment_score'], df['sentiment_magnitude'] = zip(*results)
df.to_csv('analyzed_reviews.csv', index=False)

st.write("Sentiment Analysis Results:")
st.dataframe(df.head())

# Example of additional visualization
st.line_chart(df['sentiment_score'])
